- name: Remove hostname from /etc/hosts
  become: True
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.0\.1|::1)[ \t]+{{ ipa.hostname }}.*$'
    state: absent

- name: Install IPA server
  become: True
  shell: |
    /usr/sbin/ipa-server-install --unattended          \
      --realm={{ ipa.domain | upper | quote }}         \
      --domain={{ ipa.domain | quote }}                \
      --ds-password={{ ipa.password | quote }}         \
      --admin-password={{ ipa.password | quote }}      \
      --hostname={{ ipa.fqn | quote }}                 \
      --setup-dns                                      \
      --auto-forwarders                                \
      --auto-reverse                                   \
      --no-dnssec-validation                           \
      --no-host-dns
  register: ipa_installation
  args:
    creates: /etc/ipa/default.conf

- name: Remove vagrant IP addresses from /etc/hosts because they can change over time
  become: True
  lineinfile:
    path: /etc/hosts
    regexp: '^(?!{{ ipa.ip }}).*master.ipa.vm master$'
    state: absent
  register: etc_hosts

- name: Create /etc/NetworkManager/conf.d/disable_dns.conf
  become: True
  template:
    src: disable_dns.conf
    dest: /etc/NetworkManager/conf.d/disable_dns.conf
    owner: root
    group: root
    mode: 0644
  register: nm_conf

- name: Restart NetworkManager
  become: True
  service:
    name: NetworkManager.service
    enabled: yes
    state: restarted
  when: etc_hosts.changed or nm_conf.changed

- name: Remove vagrant DNS A records
  shell: |
    echo {{ ipa.password | quote }} | kinit admin

    ipa dnsrecord-show {{ item.zone | quote }} {{ item.name | quote }} | grep {{ item.ip | quote }}
    if [ $? -ne 0 ]; then
      echo "Record {{ item.ip | quote }} in {{ item.name | quote }}.{{ item.zone | quote }} is not present. Nothing to do."
      exit 255
    fi
    
    ipa dnsrecord-del {{ item.zone | quote }} {{ item.name | quote }} \
      --a-rec={{ item.ip | quote }}
  register: result
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"
  with_items:
  - { zone: '{{ ipa.domain }}', name: 'ipa-ca', ip: '{{ ansible_default_ipv4.address }}'}
  - { zone: '{{ ipa.domain }}', name: '{{ ipa.hostname }}', ip: '{{ ansible_default_ipv4.address }}'}
