---
fedora_releasever: 28
base_box_url: https://download.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-28-1.1.x86_64.vagrant-libvirt.box

repo_fedora_enabled: 1
repo_updates_enabled: 1
repo_updates_testing_enabled: 0
repo_freeipa_copr_enabled: 1
