---
# tasks file for win-ad-forest
- name: Push script to Windows machine
  win_template:
    src: Install-ADDSForest.ps1.j2
    dest: 'C:\Windows\Temp\Install-ADDSForest.ps1'

- name: Promote to Forest Domain controller
  win_shell: 'C:\Windows\Temp\Install-ADDSForest.ps1'

- name: Restart
  win_reboot:
    test_command: 'Get-ADUser -Filter {Name -eq "Administrator"}'

- import_tasks: certificate-authority.yaml
