---
deploy_ssh_key: false
enable_nested_virt: false
create_systemd_unit: false
cloud_conf_dir: /root/.aws
ssh_key_dir: /root/.ssh
monitored_repo_owner: freeipa
monitored_repo_name: freeipa
pr_ci_repo_owner: freeipa
pr_ci_repo: "https://github.com/{{ pr_ci_repo_owner }}/freeipa-pr-ci"
pr_ci_repo_branch: master
no_task_backoff_time: 300
limit_size_systemd_journal: 300M
